#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    leftLiftPot,    sensorPotentiometer)
#pragma config(Sensor, in8,    rightLiftPot,   sensorPotentiometer)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           Left_Front_Drive, tmotorVex393TurboSpeed_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,           Left_Back_Drive, tmotorVex393TurboSpeed_MC29, openLoop, driveLeft, encoderPort, I2C_1)
#pragma config(Motor,  port3,           Left_Lift,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           Left_Planetary, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           Left_Claw,     tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port6,           Right_Claw,    tmotorVex393_MC29, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port7,           Right_Planetary, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           Right_Lift,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           Right_Back_Drive, tmotorVex393TurboSpeed_MC29, openLoop, driveRight, encoderPort, I2C_2)
#pragma config(Motor,  port10,          Right_Front_Drive, tmotorVex393TurboSpeed_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include "Autonomous_Programs.h"
#include "Util.h"

int auton = 0;




//ADD all autonomous choices
void displayAuton(){
	switch(auton){
	case 1:
		displayLCDCenteredString(0, "red auton");
		break;
	case -1:
		displayLCDCenteredString(0, "blue auton");
		break;
	case 0:
		displayLCDCenteredString(0, "ram auton");
		break;
	default:
		displayLCDCenteredString(0, "No auton");
		break;
	}
}





//DO NOT MODIFY
task LCDControl(){

	clearLCDLine(0);
	clearLCDLine(1);
	bool noButtonsPressed = true;
	displayAuton();
	while(true){
		if(noButtonsPressed){ // only update auton if a button is pressed AND wasn't pressed previously
			switch(nLCDButtons){
			case kButtonLeft:
				auton--;
				displayAuton();
				break;
			case kButtonCenter:
				stopTask(LCDControl);
				break;
			case kButtonRight:
				auton++;
				displayAuton();
				break;
			}
		}//if
		noButtonsPressed = !nLCDButtons; //update if there is a button currently pressed
		wait1Msec(20);
	}//while
}//task






void pre_auton(){

	bStopTasksBetweenModes = true;
	bDisplayCompetitionStatusOnLcd = false;
	startTask(LCDControl);

}


//Main Auton task
task autonomous()
{

	stopTask(LCDControl);
	switch(auton){
	case 1:
		startTask(Auton1);//redauton();
		break;
	case 0:
		//ramauton()
		break;
	case -1:
		//blueauton();
		break;
	default:
		//Don't run auton
		break;
	}

}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol(){

	// User control code here, inside the loop
	stopTask(LCDControl);
	startTask(ResetENC);
	stopTask(ResetENC);
	while (true){

		startTask(Claw);

	}

}
