#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    leftLiftPot,    sensorPotentiometer)
#pragma config(Sensor, in8,    rightLiftPot,   sensorPotentiometer)
#pragma config(Sensor, I2C_1,  leftDrive,      sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  rightDrive,     sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  LClaw,          sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  RClaw,          sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,            ,             tmotorVex393TurboSpeed_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,           Left_Drive,    tmotorVex393TurboSpeed_MC29, openLoop, driveLeft, encoderPort, I2C_4)
#pragma config(Motor,  port3,           Left_Lift,     tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port4,           Left_Planetary, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           Left_Claw,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           Right_Claw,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Right_Planetary, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           Right_Lift,    tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port9,           Right_Drive,   tmotorVex393TurboSpeed_MC29, openLoop, driveRight, encoderPort, I2C_3)
#pragma config(Motor,  port10,           ,             tmotorVex393TurboSpeed_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include "Autonomous_Programs.h"
#include "rerun.c"
#include "lib.h"

#define armPID(fInput) (fInput - ((SensorValue[I2C_1] + SensorValue[I2C_2]) / 2)) * 0.7


int autonomous1[150][3] = {
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0},
{0, 0, 0}};





void
tank (int iSpeedL, int iSpeedR) {
	motor[port1] = iSpeedL;
	motor[port10] = iSpeedR;
}

void
arm (int iSpeed) {
	motor[port3] = iSpeed;
	motor[port4] = iSpeed;
	motor[port7] = iSpeed;
	motor[port8] = iSpeed;
}





void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
  bDisplayCompetitionStatusOnLcd = false;
}


void
replay1 () {
	for (int i = 0; i < 150; i++) {
		arm (armPID(autonomous1[i][0]));
		tank (autonomous1[i][2], autonomous1[i][1]);
		delay(100);
	}
}



/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{

	//startTask(DriveForward);
	replay1();

}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol(){

	// User control code here, inside the loop
	while (true){

		motor[Left_Drive] = vexRT[Ch3] + vexRT[Ch1];
		motor[Right_Drive] = vexRT[Ch3] - vexRT[Ch1];

		if(vexRT[Btn5D] == true){

			motor[Left_Lift] = 127;
			motor[Left_Planetary] = 127;
			motor[Right_Planetary] = 127;
			motor[Right_Lift] = 127;

		}else if(vexRT[Btn5U] == true){

			motor[Left_Lift] = -127;
			motor[Left_Planetary] = -127;
			motor[Right_Planetary] = -127;
			motor[Right_Lift] = -127;

		}else{

			motor[Left_Lift] = 0;
			motor[Left_Planetary] = 0;
			motor[Right_Planetary] = 0;
			motor[Right_Lift] = 0;

		}

		if(vexRT[Btn6U] == true){

			motor[Left_Claw] = 127;
			motor[Right_Claw] = 127;

		}else if(vexRT[Btn6D] == true){

			motor[Left_Claw] = -127;
			motor[Right_Claw] = -127;

		}else{

			motor[Left_Claw] = 0;
			motor[Right_Claw] = 0;

		}


		if (vexRT[Btn7D]) {
			waitForReleased7D();
			startTask(record);
		}

	}

}
